/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallRouteImport } from './routes/wall'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPredictionsRouteImport } from './routes/dashboard.predictions'
import { Route as DashboardLiveTrainsRouteImport } from './routes/dashboard.live-trains'
import { Route as DashboardIncomingRouteImport } from './routes/dashboard.incoming'
import { Route as DashboardEspSensorRouteImport } from './routes/dashboard.esp-sensor'
import { Route as DashboardDigitalTwinRouteImport } from './routes/dashboard.digital-twin'
import { Route as DashboardCrowdRouteImport } from './routes/dashboard.crowd'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardStationsIndexRouteImport } from './routes/dashboard.stations.index'
import { Route as DashboardStationsStationIdRouteImport } from './routes/dashboard.stations.$stationId'
import { Route as ApiPublicEmergencyStatusRouteImport } from './routes/api/public/emergency-status'

const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionsRoute = DashboardPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveTrainsRoute = DashboardLiveTrainsRouteImport.update({
  id: '/live-trains',
  path: '/live-trains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIncomingRoute = DashboardIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEspSensorRoute = DashboardEspSensorRouteImport.update({
  id: '/esp-sensor',
  path: '/esp-sensor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDigitalTwinRoute = DashboardDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrowdRoute = DashboardCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStationsIndexRoute = DashboardStationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStationsStationIdRoute =
  DashboardStationsStationIdRouteImport.update({
    id: '/stations/$stationId',
    path: '/stations/$stationId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicEmergencyStatusRoute =
  ApiPublicEmergencyStatusRouteImport.update({
    id: '/api/public/emergency-status',
    path: '/api/public/emergency-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wall': typeof WallRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/crowd': typeof DashboardCrowdRoute
  '/dashboard/digital-twin': typeof DashboardDigitalTwinRoute
  '/dashboard/esp-sensor': typeof DashboardEspSensorRoute
  '/dashboard/incoming': typeof DashboardIncomingRoute
  '/dashboard/live-trains': typeof DashboardLiveTrainsRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/emergency-status': typeof ApiPublicEmergencyStatusRoute
  '/dashboard/stations/$stationId': typeof DashboardStationsStationIdRoute
  '/dashboard/stations/': typeof DashboardStationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wall': typeof WallRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/crowd': typeof DashboardCrowdRoute
  '/dashboard/digital-twin': typeof DashboardDigitalTwinRoute
  '/dashboard/esp-sensor': typeof DashboardEspSensorRoute
  '/dashboard/incoming': typeof DashboardIncomingRoute
  '/dashboard/live-trains': typeof DashboardLiveTrainsRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/emergency-status': typeof ApiPublicEmergencyStatusRoute
  '/dashboard/stations/$stationId': typeof DashboardStationsStationIdRoute
  '/dashboard/stations': typeof DashboardStationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wall': typeof WallRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/crowd': typeof DashboardCrowdRoute
  '/dashboard/digital-twin': typeof DashboardDigitalTwinRoute
  '/dashboard/esp-sensor': typeof DashboardEspSensorRoute
  '/dashboard/incoming': typeof DashboardIncomingRoute
  '/dashboard/live-trains': typeof DashboardLiveTrainsRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/emergency-status': typeof ApiPublicEmergencyStatusRoute
  '/dashboard/stations/$stationId': typeof DashboardStationsStationIdRoute
  '/dashboard/stations/': typeof DashboardStationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/wall'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/crowd'
    | '/dashboard/digital-twin'
    | '/dashboard/esp-sensor'
    | '/dashboard/incoming'
    | '/dashboard/live-trains'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/emergency-status'
    | '/dashboard/stations/$stationId'
    | '/dashboard/stations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/wall'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/crowd'
    | '/dashboard/digital-twin'
    | '/dashboard/esp-sensor'
    | '/dashboard/incoming'
    | '/dashboard/live-trains'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/public/emergency-status'
    | '/dashboard/stations/$stationId'
    | '/dashboard/stations'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/wall'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/crowd'
    | '/dashboard/digital-twin'
    | '/dashboard/esp-sensor'
    | '/dashboard/incoming'
    | '/dashboard/live-trains'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/emergency-status'
    | '/dashboard/stations/$stationId'
    | '/dashboard/stations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WallRoute: typeof WallRoute
  ApiPublicEmergencyStatusRoute: typeof ApiPublicEmergencyStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predictions': {
      id: '/dashboard/predictions'
      path: '/predictions'
      fullPath: '/dashboard/predictions'
      preLoaderRoute: typeof DashboardPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live-trains': {
      id: '/dashboard/live-trains'
      path: '/live-trains'
      fullPath: '/dashboard/live-trains'
      preLoaderRoute: typeof DashboardLiveTrainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/incoming': {
      id: '/dashboard/incoming'
      path: '/incoming'
      fullPath: '/dashboard/incoming'
      preLoaderRoute: typeof DashboardIncomingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/esp-sensor': {
      id: '/dashboard/esp-sensor'
      path: '/esp-sensor'
      fullPath: '/dashboard/esp-sensor'
      preLoaderRoute: typeof DashboardEspSensorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/digital-twin': {
      id: '/dashboard/digital-twin'
      path: '/digital-twin'
      fullPath: '/dashboard/digital-twin'
      preLoaderRoute: typeof DashboardDigitalTwinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crowd': {
      id: '/dashboard/crowd'
      path: '/crowd'
      fullPath: '/dashboard/crowd'
      preLoaderRoute: typeof DashboardCrowdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stations/': {
      id: '/dashboard/stations/'
      path: '/stations'
      fullPath: '/dashboard/stations/'
      preLoaderRoute: typeof DashboardStationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stations/$stationId': {
      id: '/dashboard/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/dashboard/stations/$stationId'
      preLoaderRoute: typeof DashboardStationsStationIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/emergency-status': {
      id: '/api/public/emergency-status'
      path: '/api/public/emergency-status'
      fullPath: '/api/public/emergency-status'
      preLoaderRoute: typeof ApiPublicEmergencyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardCrowdRoute: typeof DashboardCrowdRoute
  DashboardDigitalTwinRoute: typeof DashboardDigitalTwinRoute
  DashboardEspSensorRoute: typeof DashboardEspSensorRoute
  DashboardIncomingRoute: typeof DashboardIncomingRoute
  DashboardLiveTrainsRoute: typeof DashboardLiveTrainsRoute
  DashboardPredictionsRoute: typeof DashboardPredictionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStationsStationIdRoute: typeof DashboardStationsStationIdRoute
  DashboardStationsIndexRoute: typeof DashboardStationsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardCrowdRoute: DashboardCrowdRoute,
  DashboardDigitalTwinRoute: DashboardDigitalTwinRoute,
  DashboardEspSensorRoute: DashboardEspSensorRoute,
  DashboardIncomingRoute: DashboardIncomingRoute,
  DashboardLiveTrainsRoute: DashboardLiveTrainsRoute,
  DashboardPredictionsRoute: DashboardPredictionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStationsStationIdRoute: DashboardStationsStationIdRoute,
  DashboardStationsIndexRoute: DashboardStationsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WallRoute: WallRoute,
  ApiPublicEmergencyStatusRoute: ApiPublicEmergencyStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
